import 'package:powersync/powersync.dart';

/// Mirrors [infra/spend_trends] Postgres tables. PowerSync adds `id` automatically.
const Schema spendTrendsSchema = Schema([
  Table('accounts', [
    Column.text('external_id'),
    Column.text('name'),
    Column.text('currency'),
    Column.integer('balance_cents'),
    Column.integer('balance_as_of'),
    Column.text('conn_id'),
    Column.text('conn_name'),
    Column.integer('last_synced_at'),
    Column.text('status'),
    Column.text('status_message'),
    Column.text('user_label'),
    Column.text('conn_user_label'),
    Column.text('account_kind'),
    Column.text('belongs_to_account_id'),
  ]),
  Table('category_groups', [Column.text('name'), Column.integer('sort_order')]),
  Table('categories', [
    Column.text('name'),
    Column.integer('sort_order'),
    Column.integer('archived'),
    Column.text('color_token'),
    Column.text('group_id'),
  ]),
  Table('transactions', [
    Column.text('account_id'),
    Column.text('external_id'),
    Column.integer('posted_at'),
    Column.integer('amount_cents'),
    Column.text('raw_description'),
    Column.text('normalized_merchant'),
    Column.integer('pending'),
    Column.text('user_category_id'),
    Column.text('suggested_category_id'),
    Column.text('note'),
    Column.text('transaction_type'),
    Column.integer('excluded'),
    Column.text('recurring_series'),
    Column.integer('imported_at'),
  ]),
  Table('categorization_rules', [
    Column.text('match_type'),
    Column.text('pattern'),
    Column.text('category_id'),
    Column.integer('priority'),
  ]),
  Table('life_events', [
    Column.text('title'),
    Column.integer('started_on'),
    Column.integer('ended_on'),
    Column.text('note'),
  ]),
  Table('housing_stays', [
    Column.text('label'),
    Column.integer('started_on'),
    Column.text('note'),
  ]),
  Table('job_stays', [
    Column.text('label'),
    Column.integer('started_on'),
    Column.text('note'),
  ]),
  Table('sync_state', [Column.text('key'), Column.text('value')]),
  Table('simplefin_pulls', [
    Column.integer('started_at'),
    Column.integer('finished_at'),
    Column.text('kind'),
    Column.text('status'),
    Column.integer('account_count'),
    Column.integer('transaction_count'),
    Column.text('errors_json'),
  ]),
  Table('simplefin_pull_accounts', [
    Column.text('pull_id'),
    Column.text('account_id'),
    Column.text('account_external_id'),
    Column.text('conn_id'),
    Column.text('account_label'),
    Column.integer('transaction_count'),
    Column.text('status'),
    Column.text('error_message'),
  ]),
  Table('owned_assets', [
    Column.text('name'),
    Column.text('asset_kind'),
    Column.text('note'),
  ]),
  Table('owned_asset_valuations', [
    Column.text('owned_asset_id'),
    Column.integer('value_cents'),
    Column.integer('valued_on'),
  ]),
]);
